
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TheMonster
 */
public class EmpGUI extends javax.swing.JFrame {
    // class level references or attributes
    private DefaultListModel<Emp> model;
    /**
     * Creates new form StocksGUI
     */
    public EmpGUI() {
        // creat the model fo the JList
        model = new DefaultListModel<Emp>();
        
        initComponents();
        
        // set form to center of screen
        this.setLocationRelativeTo(null);
        
        //Calculate Total portfolio Value
        calculateTotalValue();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpMainTabs = new javax.swing.JTabbedPane();
        pnlAddEmp = new javax.swing.JPanel();
        lblnameF = new javax.swing.JLabel();
        txtnameF = new javax.swing.JTextField();
        txtnameL = new javax.swing.JTextField();
        lblnameL = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        lblPurchasePrice = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        btnAddEmp = new javax.swing.JButton();
        pnlEmpList = new javax.swing.JPanel();
        scrStocks = new javax.swing.JScrollPane();
        lstStocks = new javax.swing.JList<>();
        lblProfitLoss = new javax.swing.JLabel();
        btnRemoveStock = new javax.swing.JButton();
        lblTotalValue = new javax.swing.JLabel();
        mnbMainMenu = new javax.swing.JMenuBar();
        mniFile = new javax.swing.JMenu();
        mniOpen = new javax.swing.JMenuItem();
        mniSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stocks4U App");

        lblnameF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblnameF.setText("First Name:");

        txtnameF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtnameL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblnameL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblnameL.setText("Last Name:");

        txtDepartment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblPurchasePrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPurchasePrice.setText("Department:");

        txtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblID.setText("Current Price:");

        btnAddEmp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddEmp.setText("Add Employee");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddEmpLayout = new javax.swing.GroupLayout(pnlAddEmp);
        pnlAddEmp.setLayout(pnlAddEmpLayout);
        pnlAddEmpLayout.setHorizontalGroup(
            pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddEmpLayout.createSequentialGroup()
                        .addComponent(lblnameF, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnameF, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddEmpLayout.createSequentialGroup()
                        .addComponent(lblnameL, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnameL, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddEmpLayout.createSequentialGroup()
                        .addComponent(lblPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddEmpLayout.createSequentialGroup()
                        .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddEmp)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAddEmpLayout.setVerticalGroup(
            pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnameF)
                    .addComponent(txtnameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnameL)
                    .addComponent(txtnameL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPurchasePrice)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnAddEmp)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jtpMainTabs.addTab("Add Stock", pnlAddEmp);

        lstStocks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lstStocks.setModel(model);
        lstStocks.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstStocksValueChanged(evt);
            }
        });
        scrStocks.setViewportView(lstStocks);

        lblProfitLoss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProfitLoss.setText("Profit / Loss");

        btnRemoveStock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRemoveStock.setText("Remove Stock");
        btnRemoveStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStockActionPerformed(evt);
            }
        });

        lblTotalValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotalValue.setText("Total Value: ");

        javax.swing.GroupLayout pnlEmpListLayout = new javax.swing.GroupLayout(pnlEmpList);
        pnlEmpList.setLayout(pnlEmpListLayout);
        pnlEmpListLayout.setHorizontalGroup(
            pnlEmpListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEmpListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrStocks)
                    .addGroup(pnlEmpListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlEmpListLayout.createSequentialGroup()
                            .addComponent(lblProfitLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(btnRemoveStock))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEmpListLayout.setVerticalGroup(
            pnlEmpListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlEmpListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveStock)
                    .addComponent(lblProfitLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtpMainTabs.addTab("List", pnlEmpList);

        mniFile.setText("File");

        mniOpen.setText("Open");
        mniOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOpenActionPerformed(evt);
            }
        });
        mniFile.add(mniOpen);

        mniSave.setText("Save");
        mniSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaveActionPerformed(evt);
            }
        });
        mniFile.add(mniSave);
        mniFile.add(jSeparator1);

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mniFile.add(mniExit);

        mnbMainMenu.add(mniFile);

        setJMenuBar(mnbMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpMainTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpMainTabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        //Verify that the feilds are complete
        if(txtnameF.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Stock name is required.", "Error. Missing Information",JOptionPane.ERROR_MESSAGE);
            txtnameF.requestFocus();
              return;
        }
        
        if(txtnameL.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Quantity is required.", "Error. Missing Information",JOptionPane.ERROR_MESSAGE);
            txtnameL.requestFocus();
              return;
        }
        
        if(txtDepartment.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Purchase Price is required.", "Error. Missing Information",JOptionPane.ERROR_MESSAGE);
            txtDepartment.requestFocus();
              return;
        }
        
        if(txtID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Current Price is required.", "Error. Missing Information",JOptionPane.ERROR_MESSAGE);
            txtID.requestFocus();
              return;
        }
        
        double quantity = 0.0;
        try {
            quantity = Double.parseDouble(txtnameL.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid Input Please use numbers only.","Error. Invalid data",JOptionPane.ERROR_MESSAGE);
            txtnameL.requestFocus();
            return;
        }
        
        double purchasePrice = 0.0;
        try {
            purchasePrice = Double.parseDouble(txtDepartment.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid Input Please use numbers only.","Error. Invalid data",JOptionPane.ERROR_MESSAGE);
            txtDepartment.requestFocus();
            return;
        }
        
        double currentPrice = 0.0;
        try {
            currentPrice = Double.parseDouble(txtID.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid Input Please use numbers only.","Error. Invalid data",JOptionPane.ERROR_MESSAGE);
            txtID.requestFocus();
            return;
        }
        // get input
        String stockName = txtnameF.getText();
        //double quantity = Double.parseDouble(txtQuantity.getText());
        //double purchasePrice = Double.parseDouble(txtPurchasePrice.getText());
        //double currentPrice = Double.parseDouble(txtCurrentPrice.getText());
        
        //create the Emp object
        Emp stk = new Emp(stockName, quantity, purchasePrice, currentPrice);
        
        //add the Emp object to the JList
        model.addElement(stk);
        
        //Update the totalValue label
        calculateTotalValue();
        
        // reset form for the next stock
        txtnameF.setText("");
        txtnameL.setText("");
        txtDepartment.setText("");
        txtID.setText("");
        txtnameF.requestFocus();
        
    }//GEN-LAST:event_btnAddEmpActionPerformed

    private void lstStocksValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstStocksValueChanged
        // get stock and who the current profit/loss
        Emp stk = lstStocks.getSelectedValue();
        
        if(stk != null){
            double profitLoss = stk.getProfitLoss();
            DecimalFormat fmt = new DecimalFormat("#,##0.00");
            if( profitLoss > 0.0)
                lblProfitLoss.setText("Profit of " + fmt.format(profitLoss));
            else if (profitLoss < 0.0)
                lblProfitLoss.setText("Loss of " + fmt.format(profitLoss));
            else
                lblProfitLoss.setText("Break-even");
        }
    }//GEN-LAST:event_lstStocksValueChanged

    private void btnRemoveStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStockActionPerformed
        // get stock position
        int position = lstStocks.getSelectedIndex();
        
        // if selected, remove the stock
        if(position >= 0){
            model.remove(position);
            lblProfitLoss.setText("Profit / Loss");
            
            //Update the totalValue label
        calculateTotalValue();
        }
        
    }//GEN-LAST:event_btnRemoveStockActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSaveActionPerformed
    //get file name
    String fileName = JOptionPane.showInputDialog("Enter filename: ");
    

    //save data to the file
    EmpIO outToFile = new EmpIO(fileName);
    
    ArrayList<Emp> data = new ArrayList<Emp>();
    
    for(int i =0; i < model.size(); i++){
        
        Emp stk = model.elementAt(i);
        data.add(stk);
    }
    outToFile.saveData(data);
    
    JOptionPane.showMessageDialog(this, "Data was saved to the file!");
    
    }//GEN-LAST:event_mniSaveActionPerformed

    private void mniOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOpenActionPerformed
        // get the file name
        String fileName = JOptionPane.showInputDialog("Enter filename: ");
        
        //get data from the file
        EmpIO inFromFile = new EmpIO(fileName);
        
        ArrayList<Emp> data = inFromFile.getData();
        
        //clear the model and copy new data
        model.clear();
        for (int i = 0; i < data.size(); i++)
        {
            Emp stk = data.get(i);
            model.addElement(stk);
        }
        //update total value
        calculateTotalValue();
        
    }//GEN-LAST:event_mniOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnRemoveStock;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jtpMainTabs;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblProfitLoss;
    private javax.swing.JLabel lblPurchasePrice;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JLabel lblnameF;
    private javax.swing.JLabel lblnameL;
    private javax.swing.JList<Emp> lstStocks;
    private javax.swing.JMenuBar mnbMainMenu;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenu mniFile;
    private javax.swing.JMenuItem mniOpen;
    private javax.swing.JMenuItem mniSave;
    private javax.swing.JPanel pnlAddEmp;
    private javax.swing.JPanel pnlEmpList;
    private javax.swing.JScrollPane scrStocks;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtnameF;
    private javax.swing.JTextField txtnameL;
    // End of variables declaration//GEN-END:variables

    private void calculateTotalValue() {
        double totalValue = 0.0;
        
        //go through each stock in portfolio and calculate total value.
        for(int i = 0; i < model.size(); i++)
        {
            Emp stk = model.elementAt(i);
            totalValue += stk.getCurrentPrice() * stk.getNumberOfShares();
        }
        
        //show the total value
        DecimalFormat fmt = new DecimalFormat("$#,##0.00");
        lblTotalValue.setText("Total Value: " + fmt.format(totalValue));
    }
}
